kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster-1
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30008
- role: worker
- role: worker