apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      team : nginx-selector
  template :
    metadata:
      labels:
        team : nginx-selector
    spec:
      containers:
        - name: nginx
          image: nginx2
          ports:
            - containerPort: 80
               

