apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod1
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: postgres
      image: postgres
      ports:
        - containerPort: 81
      env:
        - name: POSTGRES_PASSWORD
          value: mypassword 

# LOGS : kubectl logs ngnix-pod1 -c postgres
